apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ${APP_NAME}-tls
  namespace: ${NAMESPACE}
spec:
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      - ${DOMAIN}
      - www.${DOMAIN}
      - ${ALT_DOMAIN}
      - www.${ALT_DOMAIN}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: ${APP_NAME}-tls
  commonName: ${DOMAIN}
  dnsNames:
  - ${DOMAIN}
  - www.${DOMAIN}
  - ${ALT_DOMAIN}
  - www.${ALT_DOMAIN}
---
