apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ${APP_NAME}-tls
  namespace: ${NAMESPACE}
spec:
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      - ${DOMAIN}
      - www.${DOMAIN}
      - alexos.io
      - www.alexos.io
      - www.alexmoss.co.uk
      - www.mosses.info
      - www.alexos.dev
      - www.alexos.info
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: ${APP_NAME}-tls
  commonName: ${DOMAIN}
  dnsNames:
  - ${DOMAIN}
  - www.${DOMAIN}
  - alexos.io
  - www.alexos.io
  - www.alexmoss.co.uk
  - www.mosses.info
  - www.alexos.dev
  - www.alexos.info
---
