---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alexos
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "50%"
      maxUnavailable: "50%"
  template:
    spec:
      containers:
        - name: alexos
          image: alexos:SET_BY_CI
          ports:
            - name: web
              containerPort: 32080
            - name: metrics
              containerPort: 9145
          workingDir: /app
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
            runAsGroup: 101
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /var/cache/nginx/data
              name: cache-volume
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 250Mi
      volumes:
        - name: cache-volume
          emptyDir: {}
      restartPolicy: Always
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: alexos
              topologyKey: "kubernetes.io/hostname"
            weight: 100
