---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alexos
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "50%"
      maxUnavailable: "50%"
  template:
    spec:
      containers:
        - name: alexos
          image: alexos:SET_BY_CI
          ports:
            - name: web
              containerPort: 32080
            - name: metrics
              containerPort: 9145
          workingDir: /app
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
            runAsGroup: 101
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /var/cache/nginx/data
              name: cache-volume
          # autopilot minimums
          resources:
            requests:
              cpu: 250Mi
              memory: 512Mi
            limits:
              cpu: 250Mi
              memory: 512Mi
      volumes:
        - name: cache-volume
          emptyDir: {}
      restartPolicy: Always
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      terminationGracePeriodSeconds: 25
