---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ing-${APP_NAME}
  namespace: ${NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - secretName: ${APP_NAME}-tls
    hosts:
    - ${HOSTNAME}
  rules:
  - host: ${HOSTNAME}
    http:
      paths:
      - path: /
        backend:
          serviceName: ${APP_NAME}
          servicePort: 80
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ${APP_NAME}-tls
  namespace: ${NAMESPACE}
spec:
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      - ${HOSTNAME}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: ${APP_NAME}-tls
  commonName: ${HOSTNAME}
  dnsNames:
  - ${HOSTNAME}
