---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: alexos
spec:
  parentRefs:
  - kind: Gateway
    name: shared-gateway
    namespace: ingress
  hostnames:
  - alexos.dev
  - www.alexos.dev
  - alexmoss.dev
  - www.alexmoss.dev
  rules:
  - backendRefs:
    - name: alexos
      port: 32080
