---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: alexos
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - secretName: alexos-tls
      hosts:
        - alexos.dev
        - www.alexos.dev
        - mosstech.io
        - www.mosstech.io
        - alexos.io
        - www.alexos.io
        - www.alexmoss.co.uk
        - www.mosses.info
        - www.alexos.info
  rules:
    - host: alexos.dev
      http:
        paths:
          - path: /
            backend:
              serviceName: alexos
              servicePort: 32080
    - host: www.alexos.dev
      http:
        paths:
          - path: /
            backend:
              serviceName: alexos
              servicePort: 32080
    # Entries below here pick up other domains that I direct to this blog
    # They are rewritten to the host above by some nginx config
    - host: mosstech.io
      http:
        paths:
          - path: /
            backend:
              serviceName: alexos
              servicePort: 32080
    - host: www.mosstech.io
      http:
        paths:
          - path: /
            backend:
              serviceName: alexos
              servicePort: 32080

    - host: alexos.io
      http:
        paths:
          - path: /
            backend:
              serviceName: alexos
              servicePort: 32080
    - host: www.alexos.io
      http:
        paths:
          - path: /
            backend:
              serviceName: alexos
              servicePort: 32080
    - host: www.alexmoss.co.uk
      http:
        paths:
          - path: /
            backend:
              serviceName: alexos
              servicePort: 32080
    - host: www.mosses.info
      http:
        paths:
          - path: /
            backend:
              serviceName: alexos
              servicePort: 32080
    - host: www.alexos.info
      http:
        paths:
          - path: /
            backend:
              serviceName: alexos
              servicePort: 32080
