---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-svc
  namespace: ${NAMESPACE}
  labels:
    name: ${APP_NAME}-svc
spec:
  type: NodePort
  selector:
    name: ${APP_NAME}-nginx
  ports:
  - port: 80
    name: http
---