---
apiVersion: v1
kind: Service
metadata:
  name: alexos
spec:
  type: NodePort
  ports:
    - port: 32080
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: alexos-metrics
spec:
  type: NodePort
  selector:
    app: alexos
  ports:
    - port: 9145
      name: metrics
---
apiVersion: v1
kind: Service 
metadata:     
  name: alexos-istio
spec:
  type: NodePort
  ports:
  - name: istio-proxy
    port: 15020
    protocol: TCP
