---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alexos
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: alexos
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alexos-istio
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: alexos
  endpoints:
  - interval: 30s
    path: /stats/prometheus
    port: istio-proxy
