baseURL: "https://mosstech.io"
title: "mosstech.io"
theme: "mosstech"
publishDir: "../www"
contentDir: "../content"
languageCode: "en-gb"
paginate: 10
enableEmoji: true 
googleAnalytics: "UA-119518989-2"

permalinks:
  posts: /:year/:month/:day/:title/

params:
  author: "@alexdmoss"
  description: "My blog about interesting technology - and in particular Cloud Platforms & Services, and my experiences with them"
  categoriesByCount: true

menu:
  main:
    - name: "Posts"
      pre: "<i class='far fa-newspaper'></i>"
      title: "Blog Posts"
      url: "/posts/"
      weight: 1
    - name: "About"
      pre: "<i class='far fa-id-card'></i>"
      title: "About Me"
      url: "/about/"
      weight: 2
    - name: "Contact"
      pre: "<i class='far fa-envelope'></i>"
      title: "Ways to contact me, including through this website"
      url: "/contact/"
      weight: 3
    - name: "Tags"
      pre: "<i class='fas fa-tag'></i>"
      title: "Blog posts by tag"
      url: "/tags/"
      weight: 4
    - name: "Categories"
      pre: "<i class='fas fa-box-open'></i>"
      title: "Blog posts by category"
      url: "/categories/"
      weight: 5

outputs:
  home:
  - "HTML"
  - "RSS"
  - "JSON"
