baseURL: "https://mosstech.io"
title: "mosstech.io"
theme: "mosstech"
publishDir: "../www"
contentDir: "../content"
languageCode: "en-gb"
paginate: 10


params:
  author: "@alexdmoss"
  description: "My blog about interesting technology - and in particular Cloud Platforms & Services, and my experiences with them"
  contactAPI: "http://localhost:8000/api/email/alchemyst.co.uk"


menu:
  main:
    - name: "Home"
      pre: "<i class='fas fa-home'></i>"
      title: "Home Page"
      url: "/"
      weight: 1
    - name: "About"
      pre: "<i class='far fa-id-card'></i>"
      title: "About Me"
      url: "/about/"
      weight: 2
    - name: "Posts"
      pre: "<i class='far fa-newspaper'></i>"
      title: "Blog Posts"
      url: "/posts/"
      weight: 3
    - name: "Contact"
      pre: "<i class='far fa-envelope'></i>"
      title: "Ways to contact me, including through this website"
      url: "/contact/"
      weight: 4

  # enableEmoji: true 
# enableGitInfo: true

# googleanalytics: ""
# disqusShortname: ""

# # config enables search
outputs:
  home:
  - "HTML"
  - "RSS"
  # - "JSON"

# theme: "hugo-theme-massively"

# See: https://learn.netlify.com/en/basics/configuration/
# params:
#   editURL: "https://gitlab.com/mosstech/mosstech.io/tree/master/content/"
#   commitURL: "https://gitlab.com/mosstech/mosstech.io/commit/"
#   author: "@alexdmoss"
#   description: "mosstech.io"
#   showVisitedLinks: true
#   disableSearch: false
#   # Javascript and CSS cache are automatically busted when new version of site is generated. 
#   # Set this to true to disable this behavior (some proxies don't handle well this optimization)
#   disableAssetsBusting: false
#   # Order sections in menu by "weight" or "title". Default to "weight"
#   ordersectionsby: "weight"

# menu:
#   shortcuts:
#   - name: "<i class='fas fa-book-open'></i> Markdown Examples"
#     url: "/markdown/"
#     weight: 10
#   - name: "<i class='fab fa-gitlab'></i> Git Repo"
#     url: "https://gitlab.com/mosstech/mosstech.io/"
#     weight: 20

# params:
#   posts:
#     folderName: "post"
#     pagesize: 6
#     featuredpost: true