baseURL: "https://mosstech.io"
title: "mosstech.io"
theme: "mosstech"
publishDir: "../www"
contentDir: "../content"
languageCode: "en-gb"
paginate: 10
enableEmoji: true 
googleAnalytics: "UA-119518989-2"

permalinks:
  posts: /:year/:month/:day/:title/

params:
  author: "@alexdmoss"
  description: "My blog about interesting technology - and in particular Cloud Platforms & Services, and my experiences with them"
  contactAPI: "http://localhost:8000/api/email/alchemyst.co.uk"
  categoriesByCount: true

menu:
  main:
    - name: "Home"
      pre: "<i class='fas fa-home'></i>"
      title: "Home Page"
      url: "/"
      weight: 1
    - name: "About"
      pre: "<i class='far fa-id-card'></i>"
      title: "About Me"
      url: "/about/"
      weight: 2
    - name: "Posts"
      pre: "<i class='far fa-newspaper'></i>"
      title: "Blog Posts"
      url: "/posts/"
      weight: 3
    - name: "Contact"
      pre: "<i class='far fa-envelope'></i>"
      title: "Ways to contact me, including through this website"
      url: "/contact/"
      weight: 4

# googleanalytics: ""

# # config enables search
outputs:
  home:
  - "HTML"
  - "RSS"
  - "JSON"
